name: Linux
on:
  push:
    branches-ignore:
      - '**/sources/**'
      - '**/windows/**'
      - '**/macos/**'
    paths-ignore:
      - '.github/workflows/sources.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - 'data/artwork/**'
      - 'data/packaging/macos/**'
      - 'data/packaging/windows/**'
      - 'data/platform/macos/**'
      - 'data/platform/windows/**'
      - 'docs/**'
      - '.clang-format'
      - '.git-blame-ignore-revs'
      - '.git-properties'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '.github/workflows/sources.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
      - 'data/artwork/**'
      - 'data/packaging/macos/**'
      - 'data/packaging/windows/**'
      - 'data/platform/macos/**'
      - 'data/platform/windows/**'
      - 'docs/**'
      - '.clang-format'
      - '.git-blame-ignore-revs'
      - '.git-properties'
      - 'LICENSE'
      - '**.md'

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '/debian/') }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-tags: true
        submodules: recursive
    - name: Configure container environment
      run: |
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: Parse project data
      run: |
        echo "project_version=`sed -n -E -e "/^project\(wxFormBuilder[[:space:]]+VERSION[[:space:]]+(.*)[[:space:]]+LANGUAGES.*$/{s//-\1/p;q}" CMakeLists.txt `" >> $GITHUB_ENV
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
      with:
        arch: x86_64
        bundle: wxFormBuilder${{ env.project_version }}.flatpak
        manifest-path: data/packaging/linux/flatpak/org.wxformbuilder.wxFormBuilder.json
        cache-key: flatpak-builder-${{ github.sha }}
  debian:
    name: Debian Package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, wxver: 3.2 }
          - { os: ubuntu-latest, wxver: 3.0-gtk3 }
          - { os: ubuntu-20.04, wxver: 3.0-gtk3 }
    if: ${{ !contains(github.ref, '/flatpak/') }}
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-tags: true
        submodules: recursive
    - name: Setup environment
      run: |
        sudo apt update
        sudo apt install libwxgtk${{ matrix.wxver }}-dev libwxgtk-media${{ matrix.wxver }}-dev libboost-dev debhelper fakeroot rename xvfb
    - name: Setup package build
      run: |
        cp -rf data/packaging/linux/debian/ ./debian/
        echo "package_basedir=${GITHUB_WORKSPACE%/*}" >> $GITHUB_ENV
    - name: Build package
      run: |
        dpkg-buildpackage --build=binary --no-check-builddeps --no-sign --root-command=fakeroot --jobs=auto
        rename "s/(.+_.+_)(.*)/\$1ubuntu-`lsb_release -r -s`_\$2/" "${{ env.package_basedir }}/"*.deb
    - name: Test package
      run: |
        xvfb-run --server-args="-screen 0, 1280x720x24" -a debian/wxformbuilder/usr/bin/wxformbuilder -v
        xvfb-run --server-args="-screen 0, 1280x720x24" -a debian/wxformbuilder/usr/bin/wxformbuilder -g test/wxfbTest.fbp
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: Debian Package ${{ matrix.os }}
        path: |
          ${{ env.package_basedir }}/*.deb
